version: '2'
services:
  api:
    build: .
    command: puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
  postgres:
    image: 'postgres:12.1-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
  redis:
    image: 'redis:5.0-alpine'
    volumes:
      - 'redis:/data'
  sidekiq:
    build: .
    command: sidekiq -q default -q active_storage_purge -q active_storage_analysis
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
volumes:
  redis:
  postgres:
