version: '2'
services:
  api:
    build: .
    command: puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
  postgres:
    image: 'postgres:12.1-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
  redis:
    image: 'redis:5.0-alpine'
    volumes:
      - 'redis:/data'
  sidekiq:
    build: .
    command: sidekiq -q default -q active_storage_purge -q active_storage_analysis
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    depends_on:
      - 'postgres'
      - 'redis'
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      # container_name: es01
      environment:
        - discovery.type=single-node
        - node.name=es01
        - cluster.name=justcars-docker-cluster
        # - discovery.seed_hosts=es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        # - xpack.security.enabled=false
        # - xpack.monitoring.enabled=false
        # - xpack.graph.enabled=false
        # - xpack.watcher.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - 'elasticsearch:/usr/share/elasticsearch/data'
      ports:
        - 9200:9200
      # networks:
      #   - elastic
volumes:
  redis:
    driver: local
  postgres:
    driver: local
  elasticsearch:
    driver: local

# networks:
#   elastic:
#     driver: bridge
