api_version: 0.0.1

routes:
  host: http://localhost:3000
  admin_namespace: xQp2l6Q7nN

redis:
  url: redis://redis:6379/1

sidekiq:
  username: admin
  password: Up3tj0X7Jk10

aws:
  region: eu-west-2
  bucket: artscript-development-apps
  access_key_id:
  secret_access_key:

elasticsearch:
  host: http://elasticsearch:9200
  log: true

pagination:
  per_page:
    default: 30
    minimum: 1
    maximum: 100
  page:
    default: 1
